DROP TABLE IF EXISTS questions CASCADE;

CREATE TABLE questions(
    id SERIAL PRIMARY KEY,
    question VARCHAR,
    options VARCHAR [],
    correct_answer VARCHAR

);

INSERT INTO questions (question, options, correct_answer) VALUES
('What is the capital of France?', '{"London", "Paris", "Berlin", "Rome"}', 'Paris'),
('Who wrote "Romeo and Juliet"?', '{"William Shakespeare", "Charles Dickens", "Jane Austen", "Leo Tolstoy"}', 'William Shakespeare'),
('What is the chemical symbol for water?', '{"Wa", "Wt", "H2O", "Wt2"}', 'H2O'),
('What is the largest mammal in the world?', '{"Elephant", "Blue Whale", "Giraffe", "Hippopotamus"}', 'Blue Whale'),
('Who painted the Mona Lisa?', '{"Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso", "Michelangelo"}', 'Leonardo da Vinci'),
('What is the capital of Japan?', '{"Tokyo", "Beijing", "Seoul", "Bangkok"}', 'Tokyo'),
('Which planet is known as the Red Planet?', '{"Venus", "Jupiter", "Mars", "Saturn"}', 'Mars'),
('What is the chemical symbol for gold?', '{"Au", "Ag", "Go", "Gl"}', 'Au'),
('Who discovered penicillin?', '{"Alexander Fleming", "Louis Pasteur", "Marie Curie", "Isaac Newton"}', 'Alexander Fleming'),
('What is the capital of Australia?', '{"Sydney", "Melbourne", "Canberra", "Brisbane"}', 'Canberra'),
('Who wrote "To Kill a Mockingbird"?', '{"Harper Lee", "J.K. Rowling", "George Orwell", "Ernest Hemingway"}', 'Harper Lee'),
('How many continents are there?', '{"5", "6", "7", "8"}', '7'),
('What is the chemical symbol for oxygen?', '{"Ox", "Oy", "O2", "Ox2"}', 'O2'),
('Who invented the telephone?', '{"Alexander Graham Bell", "Thomas Edison", "Albert Einstein", "Nikola Tesla"}', 'Alexander Graham Bell'),
('What is the longest river in the world?', '{"Nile", "Amazon", "Mississippi", "Yangtze"}', 'Nile'),
('What is the capital of Brazil?', '{"Rio de Janeiro", "Brasília", "São Paulo", "Salvador"}', 'Brasília'),
('Who wrote "1984"?', '{"George Orwell", "Ernest Hemingway", "Harper Lee", "J.K. Rowling"}', 'George Orwell'),
('What is the capital of India?', '{"Delhi", "Mumbai", "Kolkata", "Chennai"}', 'Delhi'),
('Who wrote "The Great Gatsby"?', '{"F. Scott Fitzgerald", "Ernest Hemingway", "Mark Twain", "Charles Dickens"}', 'F. Scott Fitzgerald'),
('What is the chemical symbol for carbon?', '{"Ca", "Cb", "C", "Cr"}', 'C'),
('Which of the following is not a primary color?', '{"Red", "Yellow", "Green", "Blue"}', 'Green'),
('Who is known as the father of modern physics?', '{"Isaac Newton", "Albert Einstein", "Galileo Galilei", "Niels Bohr"}', 'Albert Einstein'),
('What is the capital of China?', '{"Shanghai", "Beijing", "Guangzhou", "Shenzhen"}', 'Beijing'),
('Which of the following is the largest ocean?', '{"Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"}', 'Pacific Ocean'),
('What is the chemical symbol for sodium?', '{"So", "Na", "Sn", "Sa"}', 'Na'),
('Who wrote "Pride and Prejudice"?', '{"Jane Austen", "Emily Brontë", "Charlotte Brontë", "Virginia Woolf"}', 'Jane Austen'),
('Which country is known as the Land of the Rising Sun?', '{"China", "Japan", "Korea", "Vietnam"}', 'Japan'),
('What is the square root of 64?', '{"6", "8", "10", "12"}', '8'),
('Who painted "Starry Night"?', '{"Vincent van Gogh", "Pablo Picasso", "Claude Monet", "Leonardo da Vinci"}', 'Vincent van Gogh'),
('What is the chemical symbol for iron?', '{"Ir", "Fe", "In", "Fu"}', 'Fe'),
('Who is credited with discovering gravity?', '{"Isaac Newton", "Albert Einstein", "Galileo Galilei", "Niels Bohr"}', 'Isaac Newton'),
('Which gas do plants use for photosynthesis?', '{"Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"}', 'Carbon Dioxide'),
('What is the capital of Russia?', '{"Moscow", "St. Petersburg", "Novosibirsk", "Yekaterinburg"}', 'Moscow'),
('Who wrote "The Catcher in the Rye"?', '{"J.D. Salinger", "F. Scott Fitzgerald", "Ernest Hemingway", "Mark Twain"}', 'J.D. Salinger'),
('What is the chemical symbol for silver?', '{"Si", "Ag", "Sv", "Sl"}', 'Ag'),
('Which planet is known as the "Morning Star" or "Evening Star"?', '{"Venus", "Mercury", "Mars", "Jupiter"}', 'Venus'),
('What is the boiling point of water in Celsius?', '{"100°C", "0°C", "50°C", "200°C"}', '100°C'),
('Who wrote "War and Peace"?', '{"Leo Tolstoy", "Fyodor Dostoevsky", "Anton Chekhov", "Nikolai Gogol"}', 'Leo Tolstoy'),
('What is the chemical symbol for potassium?', '{"K", "Po", "Ka", "Ke"}', 'K'),
('What is the largest organ in the human body?', '{"Liver", "Lungs", "Heart", "Skin"}', 'Skin'),
('Who discovered the theory of relativity?', '{"Albert Einstein", "Isaac Newton", "Galileo Galilei", "Niels Bohr"}', 'Albert Einstein'),
('What is the capital of South Africa?', '{"Cape Town", "Pretoria", "Johannesburg", "Durban"}', 'Pretoria'),
('Who wrote "Moby-Dick"?', '{"Herman Melville", "Nathaniel Hawthorne", "Edgar Allan Poe", "Mark Twain"}', 'Herman Melville'),
('What is the chemical symbol for helium?', '{"He", "H", "Ha", "Hu"}', 'He'),
('Who composed the "Moonlight Sonata"?', '{"Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Franz Schubert"}', 'Ludwig van Beethoven'),
('What is the melting point of ice in Celsius?', '{"0°C", "100°C", "-10°C", "50°C"}', '0°C'),
('What is the largest ocean in the world?', '{"Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"}', 'Pacific Ocean'),
('Who is known as the "Father of Medicine"?', '{"Hippocrates", "Aristotle", "Plato", "Socrates"}', 'Hippocrates'),
('Which country is known as the Land of the Rising Sun?', '{"China", "Japan", "Korea", "Vietnam"}', 'Japan'),
('What is the chemical symbol for helium?', '{"He", "H", "Ha", "Hu"}', 'He'),
('Who composed the "Moonlight Sonata"?', '{"Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Franz Schubert"}', 'Ludwig van Beethoven'),
('What is the melting point of ice in Celsius?', '{"0°C", "100°C", "-10°C", "50°C"}', '0°C'),
('Who is the author of "The Odyssey"?', '{"Homer", "Virgil", "Sophocles", "Plato"}', 'Homer'),
('What is the chemical symbol for potassium?', '{"K", "Po", "Ka", "Ke"}', 'K'),
('Which planet is known as the "Red Planet"?', '{"Venus", "Jupiter", "Mars", "Saturn"}', 'Mars'),
('What is the boiling point of water in Celsius?', '{"100°C", "0°C", "50°C", "200°C"}', '100°C'),
('Who painted the ceiling of the Sistine Chapel?', '{"Leonardo da Vinci", "Raphael", "Michelangelo", "Donatello"}', 'Michelangelo'),
('What is the chemical symbol for iron?', '{"Ir", "Fe", "In", "Fu"}', 'Fe'),
('What is the smallest bone in the human body?', '{"Femur", "Stapes", "Humerus", "Radius"}', 'Stapes'),
('Which famous scientist is best known for his theory of gravity?', '{"Isaac Newton", "Albert Einstein", "Galileo Galilei", "Stephen Hawking"}', 'Isaac Newton'),
('Who is credited with inventing the World Wide Web?', '{"Tim Berners-Lee", "Bill Gates", "Steve Jobs", "Mark Zuckerberg"}', 'Tim Berners-Lee'),
('Which ocean is the largest?', '{"Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"}', 'Pacific Ocean');

